"""Initial migration

Revision ID: d90cfb3756b4
Revises: 
Create Date: 2025-11-24 18:46:16.707038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90cfb3756b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CONSUMABLE', 'PERMANENT', name='type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='unique_user_product')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('transaction_status_created_at_idx', 'transaction', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'COMPLETED'"))

    # Create some test data

    op.execute(
        """
        INSERT INTO "user" (username, email, balance, created_at)
        VALUES ('user1', 'user1@example.com', 100, NOW()),
               ('user2', 'user2@example.com', 200, NOW()),
               ('user3', 'user3@example.com', 300, NOW()),
               ('user4', 'user4@example.com', 400, NOW()),
               ('user5', 'user5@example.com', 500, NOW());
        """
    )

    op.execute(
        """
        INSERT INTO "product" (name, description, price, type, is_active, created_at)
        VALUES ('Product1', 'Description1', 100, 'CONSUMABLE', TRUE, NOW()),
               ('Product2', 'Description2', 200, 'PERMANENT', TRUE, NOW()),
               ('Product3', 'Description3', 300, 'CONSUMABLE', TRUE, NOW()),
               ('Product4', 'Description4', 400, 'PERMANENT', TRUE, NOW()),
               ('Product5', 'Description5', 500, 'CONSUMABLE', TRUE, NOW());
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transaction_status_created_at_idx', table_name='transaction', postgresql_where=sa.text("status = 'COMPLETED'"))
    op.drop_table('transaction')
    op.drop_table('inventory')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###